import { db } from "@/firebase/firebase";
import { User } from "firebase/auth";
import { onValue, ref } from "firebase/database";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

interface Comment {
  userName: string;
  comment: string;
  photoUrl: string;
}

interface Goal {
  name: string;
  description: string;
  // steps:Array<string> | null,
  user: User;
  comments: Array<Comment> | null;
}

export default function Home() {
  const [goals, setGoals] = useState<unknown>([]);

  const goalsRef = ref(db, "goals");

  // useEffect(() => {
  //   onValue(goalsRef, (snapshot) => {
  //     const data = snapshot.val();
  //     let goalRes = [];
  //     for (let value of Object.values(data)) {
  //       goalRes.push(value);
  //     }
  //     setGoals(goalRes);
  //   });
  // }, []);

  console.log(goals);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        {/* {goals &&
          goals.map((goal: Goal, index: number) => {
            return (
              <Link href={`/${goal.user.uid}`} key={index}>
                <p>{goal.name}</p>
                <p>{goal.description}</p>
              </Link>
            );
          })} */}
      </main>
    </>
  );
}
